// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ContactButton() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"contact-links\"><div class=\"md\"><a href=\"https://github.com/levifitzpatrick1\" target=\"_blank\" rel=\"noopener noreferrer\">Github</a></div><div x-data=\"{ feedback: 'Personal Email: levifitzpatrick1@gmail.com' }\"><button x-on:click=\"\r\n\t\t\t\t\t\t\t\t\tnavigator.clipboard.writeText('levifitzpatrick1@gmail.com');\r\n\t\t\t\t\t\t\t\t\tfeedback = 'Copied!';\r\n\t\t\t\t\t\t\t\t\tsetTimeout(() => { feedback = 'Personal Email: levifitzpatrick1@gmail.com' }, 2000);\r\n\t\t\t\t\t\t\t\t\" class=\"inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 transition-colors\"><span x-text=\"feedback\"></span></button></div></div><div x-data=\"{ feedback: 'FRC Email: levi@2064.team' }\"><button x-on:click=\"\r\n\t\t\t\tnavigator.clipboard.writeText('levi@2064.team');\r\n\t\t\t\tfeedback = 'Copied!';\r\n\t\t\t\tsetTimeout(() => { feedback = 'FRC Email: levi@2064.team' }, 2000);\r\n\t\t\t\" class=\"inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-sky-600 hover:bg-sky-700 transition-colors\"><span x-text=\"feedback\"></span></button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
