// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package blogs

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/levifitzpatrick1/blog/web/templates/layouts"
import "github.com/levifitzpatrick1/blog/internal/utils"
import "github.com/levifitzpatrick1/blog/web/templates/components/blog"

func Blogs(data []utils.Post) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"w-full min-h-screen\"><div class=\"my-8 flex justify-center px-4\"><div class=\"w-full mx-auto md:w-2/3 lg:w-1/2\"><div class=\"relative search-container border-b border-border focus-within:border-accent transition-colors duration-200\"><input class=\"w-full bg-transparent text-primary py-3 pr-10 focus:outline-none placeholder-secondary/50 text-base\" type=\"search\" name=\"search\" placeholder=\"Search posts...\" hx-post=\"/search\" hx-trigger=\"input changed delay:120ms, search\" hx-target=\"#blog-results\" hx-indicator=\"closest .search-container\" hx-swap=\"innerHTML transition:true\"><div class=\"absolute right-0 top-1/2 transform -translate-y-1/2 flex items-center justify-center pointer-events-none\"><span id=\"search-indicator\" class=\"htmx-indicator material-symbols-outlined text-xl text-accent animate-spin leading-none\">progress_activity</span> <span id=\"search-icon\" class=\"search-icon material-symbols-outlined text-xl text-secondary/50 leading-none\">search</span></div></div></div></div><div id=\"blog-results\" class=\"max-w-7xl mx-auto px-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = blog.PostCardList(data).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Sub("Blog", "/blog", layouts.HtmxScript()).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
