// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/levifitzpatrick1/levifitzpatrick.page/web/templates/layouts"
import "github.com/levifitzpatrick1/levifitzpatrick.page/internal/utils"

func Home(latestPost utils.Post) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"w-full min-h-screen\"><div class=\"text-center pt-12 pb-16 sm:pt-16 sm:pb-20 slide-up\"><h1 class=\"text-5xl md:text-6xl text-white font-bold mb-8\">Levi Fitzpatrick</h1><div class=\"flex flex-col sm:flex-row justify-center gap-4\"><a href=\"/frc\" class=\"btn-material bg-background text-accent border-2 border-accent font-bold py-4 px-10 rounded-xl transition-all duration-300\">FRC</a> <a href=\"/blog\" class=\"btn-material bg-background text-accent border-2 border-accent font-bold py-4 px-10 rounded-xl transition-all duration-300\">Blog</a> <a href=\"/packout/\" class=\"btn-material bg-background text-accent border-2 border-accent font-bold py-4 px-10 rounded-xl transition-all duration-300\">Packout</a></div></div><div class=\"max-w-2xl mx-auto px-4 pb-12 text-center fade-in\"><p class=\"text-secondary text-xl leading-relaxed\">I am Levi Fitzpatrick. This site is a place for me to store posts about projects and Ideas that I have, and are currently, working on. Many of the posts here will end up being related to designing FRC Robots both in mechanical and software scopes. I am currently a lead mentor of FRC Team 2064 Panther Project, mainly filling the role of software engineer mentor. This stems from my career choice of a mechanical engineer masquerading as a software engineer.</p></div><div class=\"text-center py-12 px-4 fade-in\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if latestPost.Title != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"max-w-2xl mx-auto\"><h2 class=\"text-2xl font-bold text-primary mb-4\">Latest Post</h2><a href=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 templ.SafeURL
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinURLErrs(templ.URL("/blog/" + latestPost.Slug))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/Pages/Home/home.templ`, Line: 50, Col: 51}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" class=\"block group\"><p class=\"text-xl text-accent font-semibold truncate-3-lines hover:text-accent/80 transition-all duration-300\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(latestPost.Blurb)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/Pages/Home/home.templ`, Line: 54, Col: 26}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</p></a></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><div class=\"text-center py-16 px-4 fade-in border-t border-border mt-12 max-w-2xl mx-auto\"><h2 class=\"text-2xl font-bold text-primary mb-6\">Contact</h2><div class=\"flex flex-col sm:flex-row justify-center items-center gap-6 text-base\"><a href=\"https://github.com/levifitzpatrick1\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"font-semibold text-secondary hover:text-accent transition-colors duration-200\">GitHub</a> <span class=\"text-border hidden sm:inline\">&bull;</span> <a href=\"mailto:levifitzpatrick1@gmail.com\" class=\"font-semibold text-secondary hover:text-accent transition-colors duration-200\">Personal Email</a> <span class=\"text-border hidden sm:inline\">&bull;</span> <a href=\"mailto:levi@2064.team\" class=\"font-semibold text-secondary hover:text-accent transition-colors duration-200\">FRC Email</a></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base("Levi Fitzpatrick - Portfolio").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
